---
title:  CFT for Particle Physicists
output: 
  html_document:
    toc: true
    number_sections: true    
bibliography: [./bib/phys.bib ]      
link-citations: true
---
 
 
# CFT for Particle Physicists {#CFT4hepph}

## Preface {-}
Reading [@gillioz2022conformal]

- Two more symmetries: scale symmetry, and special conformal symmetry
  - Modern conformal bootstrap!
  - Unitarity bounds derived from the spectral representation!
  - Appearance of UV and IR divergences!
  
## Ch1: Intro

- New Definition:
\begin{align}
  \mathrm{CFT}  =& \mathrm{RQFT}  \\
        &+ \mathrm{Scale Sym}\\
       &+ \mathrm{Special-Conformal Sym}
\end{align}
  - RQFT: flat-Minkowski, Wightman axioms, and all that.
  - Scale Sym: RG, no-mass gap, and all that
  - Special-Conformal Sym: conformal correlation functions, OPE(!), conformal bootstrap(!!)
  
  
## Ch2: C(lassical)-CFT
- The physical symmetry is a special transformation enjoyed by a physical system, and in the most general term it can be set up tentatively (without putting requirement at all) as: 
$$
  x^\mu \rightarrow x'^\mu = x^\mu + \varepsilon^\mu(x) + \mathcal{O}(\varepsilon^2)
$$
- The Physical distance, aka $ds = g_{\mu\nu}(x) dx^\mu dx^\nu$
  - Either Eucliean $\delta_{\mu\nu}$ or Minskowski $\eta_{\mu\nu}$
  - Distance being physical, aka invariant under valid physically sensible transformation: 
$$
  g'_{\mu\nu}(x') dx'^\mu dx'^\nu = g_{\alpha\beta}(x) dx^\alpha dx^\beta
$$
  - Assuming the metric is flat, aka $\partial_{\alpha} g_{\mu\nu} \equiv 0$, then
  
\begin{align}
  g'_{\mu\nu}(x')  =&  
  g_{\alpha\beta}
  \frac{\partial x^\alpha}{\partial x'^\mu}
  \frac{\partial x^\beta}{\partial x'^\nu} \\
  =& g_{\alpha\beta} 
  (\delta^\alpha_\mu - \partial_\mu \varepsilon^\alpha)
  (\delta^\beta_\nu - \partial_\nu \varepsilon^\beta) 
  + \mathcal{O}(\varepsilon^2) \\
  =&  g_{\mu\nu} - \partial_\mu \varepsilon_\nu - \partial_\nu \varepsilon_\mu 
  + \mathcal{O}(\varepsilon^2) 
\end{align}

- Therefore, in a flat metric, for the distance to be preserved, the would-be good physical symmetry cannot be arbitrary in that it needs to obey the constrain of $\partial_\mu \varepsilon_\nu + \partial_\nu \varepsilon_\mu \overset{!}{=} 0$.
  - The most general solution: $\varepsilon_\mu = a^\mu + \omega_{\mu\nu}(x) x^\nu$, with $a^\mu$ be a constant, and $\omega_{\mu\nu}$ be anti-symmetric tensor.
    - $[a^\mu|x^\mu\rightarrow{x^\mu+a^\mu}]$, the translation group!
    - $[\omega_{\mu\nu}|x^\mu\rightarrow{x^\mu+\omega_{\mu\nu}x^\nu}]$: the rotation group!
      - $[a^\mu,\omega_{\mu\nu}]$, the Poincare group!
 
 
# Reference   
